name: Main CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cmd:
        - lint
        - test
        - build
    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: just ${{ matrix.cmd }}

  push-image:
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'
    needs: ci
    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v4
      - run: just image
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - run: podman push quay.io/mmoltras/vulma
